[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tkn_launcher = "8M6CDsJj8JNjxKaWBHpPLdJmDJLvaDWmhsNeXR2GDHnp"
token = "Hb6gtVLrVawERsruS1Mq5y5uqSR5QTzD8AMjYKr4uwED"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/empiric-u3/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
