[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pool = "DtaiArZWpxECk7mw9cM5ccsstWTxc8XKDoxZDTfJjz2z"
token_program = "3hpMH7KnWCaG9PX4qv1SSCiF1mzTFdMLa9PigM4BW4ti"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/hp/.config/solana/solana_account1.json"

[workspace]
members = ["programs/token-program", "programs/pool"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
