[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]

pool = "2w7YpkzHHEUvGLh1GAou8VDr9Zcn6CWhRUvGjCUdcaPB"
token_program = "6JAaDkZ58YL1AsoovBKvZS4VGPG5GhGDcckxuh5ze7Bt"

[workspace]
members = ["programs/token-program", "programs/pool"]

[deploy]
pool = "pool"
token_program = "token_program"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hp/.config/solana/solana_account1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
