[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pool = "CgeQdEqXnFafzo9qm6BtMMZ4HirKboxxDHDqee7yDNTu"
# spltoken = "9es2vf5nnqkfbjczhko6wu7AXBA8w9pmR41jjC2Wwrv8"
token_program = "Efp5ixWb3y3kfa9act9FGz2u5mb29CGWtiVwBphmri5i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/empiric-u3/.config/solana/id.json"

[workspace]
members = ["programs/token-program", "programs/pool"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
